export const PLANETS = [
  { key: 'mercury', number: '01', name: 'Mercury', subtitle: 'Closest to the fire', title: 'Small world. Extreme conditions.', description: 'A cratered, ancient world racing around the Sun. Mercury completes an orbit in just 88 days, with almost no atmosphere to soften the extremes.', distance: '57.9 million', year: '0.24', diameter: '4,879', type: 'Terrestrial', radius: 0.46, orbit: 7, period: 0.24, tilt: 0.03, phase: 2.5, color: '#a89d8e', palette: ['#464440','#898278','#b9afa2'] },
  { key: 'venus', number: '02', name: 'Venus', subtitle: 'Beauty under pressure', title: 'Our brilliantly inhospitable neighbor.', description: 'Wrapped in thick clouds, Venus shines brightly in our sky. Beneath that pale veil lies a volcanic landscape and the hottest surface of any planet.', distance: '108 million', year: '0.62', diameter: '12,104', type: 'Terrestrial', radius: 0.8, orbit: 10, period: 0.62, tilt: 177, phase: 5.0, color: '#d8ae73', palette: ['#9c6f35','#d9ac65','#f2d9a0'] },
  { key: 'earth', number: '03', name: 'Earth', subtitle: 'Our pale blue home', title: 'Everything we know. Everyone we love.', description: 'An ocean world, wrapped in a thin atmosphere. Earth is the only planet we know with liquid oceans on the surface and life among the stars.', distance: '150 million', year: '1', diameter: '12,742', type: 'Terrestrial', radius: 0.86, orbit: 14, period: 1, tilt: 23.4, phase: 0.4, color: '#75b5df', palette: ['#052847','#0d5178','#3284a0'] },
  { key: 'mars', number: '04', name: 'Mars', subtitle: 'The red planet', title: 'The next chapter of discovery.', description: 'Rust-red deserts, towering volcanoes, and traces of ancient rivers. Our neighboring world holds a billion-year story — and a future we’re still imagining.', distance: '228 million', year: '1.88', diameter: '6,779', type: 'Terrestrial', radius: 0.6, orbit: 18, period: 1.88, tilt: 25.2, phase: 3.1, color: '#d99769', palette: ['#663f2d','#ae6d45','#dca271'] },
  { key: 'jupiter', number: '05', name: 'Jupiter', subtitle: 'King of the planets', title: 'A giant with a storm to match.', description: 'A sweeping world of cloud bands and colossal storms. Jupiter’s Great Red Spot has swirled for centuries, while dozens of moons make up a system of their own.', distance: '778 million', year: '11.86', diameter: '139,820', type: 'Gas giant', radius: 2.55, orbit: 28, period: 11.86, tilt: 3.1, phase: 0.95, color: '#d8b18c', palette: ['#815c43','#bd9371','#e1c6a4'] },
  { key: 'saturn', number: '06', name: 'Saturn', subtitle: 'The ringed giant', title: 'A world with a signature.', description: 'Billions of pieces of ice and rock. One extraordinary silhouette. Saturn reminds us that the most beautiful things are often a little unconventional.', distance: '1.4 billion', year: '29.4', diameter: '116,460', type: 'Gas giant', radius: 2.1, orbit: 39, period: 29.4, tilt: 26.7, phase: 3.7, color: '#dcc8a0', palette: ['#9c895e','#cfbb8b','#eddfb7'] },
  { key: 'uranus', number: '07', name: 'Uranus', subtitle: 'A world turned sideways', title: 'Following its own direction.', description: 'A quiet blue-green world with an extraordinary tilt. Uranus rotates almost on its side, giving it some of the most extreme seasons in the solar system.', distance: '2.9 billion', year: '84', diameter: '50,724', type: 'Ice giant', radius: 1.35, orbit: 50, period: 84, tilt: 97.8, phase: 2.0, color: '#a0d9d7', palette: ['#5ba3ad','#8cc8cd','#b2e2df'] },
  { key: 'neptune', number: '08', name: 'Neptune', subtitle: 'Beyond the blue', title: 'A beautiful kind of far away.', description: 'At the edge of our planetary neighborhood, an ice giant dances in the dark. Neptune’s winds race through an atmosphere where sunlight is only a distant whisper.', distance: '4.5 billion', year: '165', diameter: '49,244', type: 'Ice giant', radius: 1.25, orbit: 61, period: 165, tilt: 28.3, phase: 5.45, color: '#658de3', palette: ['#203d89','#3c64b6','#669ce5'] }
];
export const planetByKey = Object.fromEntries(PLANETS.map(planet => [planet.key, planet]));
